"""added trip table

Revision ID: 46803c822046
Revises: 0e5b797e5dec
Create Date: 2024-04-22 11:24:23.124408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46803c822046'
down_revision = '0e5b797e5dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city_state', sa.String(), nullable=True),
    sa.Column('vacation_type', sa.String(), nullable=True),
    sa.Column('cover_image', sa.String(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trips'))
    )
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_attendances_trip_id_trips'), 'trips', ['trip_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_attendances_trip_id_trips'), type_='foreignkey')
        batch_op.drop_column('trip_id')

    op.drop_table('trips')
    # ### end Alembic commands ###
