"""added at updated column for post

Revision ID: 481828ec3bbb
Revises: 72b98da478da
Create Date: 2024-05-04 04:30:49.354310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481828ec3bbb'
down_revision = '72b98da478da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
