"""remove age column from users table

Revision ID: 542aa5a7821d
Revises: fd352819e350
Create Date: 2024-04-23 10:31:27.654148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542aa5a7821d'
down_revision = 'fd352819e350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.INTEGER(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
